apiVersion: v1
kind: Service
metadata:
  name: service3
  labels:
    app: service3
    service: service3
spec:
  selector:
    app: service3
    service: service3
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP